### ISSUE TITLE
[ Potential Race Condition ] Temporary dialable table gets emptied while in the middle of being sent to CopyDialableTable(t)

### ISSUE THREAD

**Issue by Renniej** [Zytharian/RbxStargate#5]
I noticed that when using the stargate remote that one of my stargates wouldn't recognize  the others.  After tedious breakpoints it seems to come down to "StargateScript" line 1229 where the table is sent off to be copied.  Before being sent off and copied I have a proper table of all the stargates that should be recognized [Image Below + following details] 

![image](https://user-images.githubusercontent.com/17017622/173452074-aca45e49-fc97-489a-9649-9ceba17ee390.png)

However right when it is sent to the copyDialableTable function the table somehow gets empitied. Almost like it's being modified from somewhere else.  NOTE: I removed the teleportAddresses entries from  StargateConfig    [Image Below +  More Details]  

![image](https://user-images.githubusercontent.com/17017622/173452373-2cd9e898-cfea-40e5-9746-a5f4ab559956.png)

This got me curious so I looked into a gate where I hadn't removed the teleportAddresses from StargateConfig and there is def something weird going on.  Before the copyDialableTable is called everything is great and my gates are recognized.

![image](https://user-images.githubusercontent.com/17017622/173452919-5bfe1997-00f8-419d-ac88-0421c26dabbb.png)

But once it hits the copyDialabl table function all of sudden 3 new entries from the teleportAddresses are added???????? [Image Below]

![image](https://user-images.githubusercontent.com/17017622/173453121-76108d5e-23e0-469c-81ae-d66aebec5945.png)

I thought maybe it was a metatable function going off but that's not possible because no metatable is set for the temporary dialable variable

**Comment by Zytharian** [comment]
This isn't a race condition. Note that `dialable` gets defined at the beginning of the function and then shadowed (re-defined) right after the `-- Remove duplicates` comment so there are actually two variables of the same name. It is the second one that gets sent to `copyDialableTable()` but only the first is shown in the debugger which is where this confusion is coming from. It's a fair code style issue - I should make `diabable` not be shadowed.

You can rename the shadowed variable and the places it is used in the function in order to use the debugger to investigate more. Likely what's happening is the two gates are determined to be duplicates and dropped from the dialable list or their address violates the gate's minLength/maxLength settings.

**Comment by Renniej** [comment]
Ya, I ended up re-coding your "Remove Duplicate, respecting priority"  and it fixed all the issues.  (this doesn't use shadowing and instead directly interacts with the original dialable table.

```

 -- Remove duplicates, respecting priority
	local entryShift = 0
	for i,entry in pairs(dialable) do
		for g,toCheck in pairs(dialable) do

			if i ~= g then

				local potentialDup = table.concat(toCheck.DialAddress)
				local curEntry = table.concat(entry.DialAddress)

				if curEntry == potentialDup then
					table.remove(dialable, i - entryShift)
					entryShift += 1
				end
			end
		end
	end
```

**Comment by Zytharian** [comment]
Can you show under what cases the current algorithm fails to properly de-duplicate entries in `dialable`?

Also: your code does not actually work. You're making the classic mistake of iterating over something that you're modifying. For example if dialable was 
```local dialable={{DialAddress={"A"}}, {DialAddress={"B"}}, {DialAddress={"A"}}, {DialAddress={"A"}}}```
then the result of your code will be 
```{{DialAddress={"A"}}, {DialAddress={"A"}}}```
but it should be
```{{DialAddress={"B"}}}```
because there's no way to decide which Stargate the address should lead to for the "A" duplicates -- at least without a priority.

**Comment by Renniej** [comment]
Huh, you're absolutely correct.  Seems im also missing something here. I wouldn't mind doing a quick discord call with you to go over the use case that's causing the original bug.

**Comment by Zytharian** [comment]
I'm willing to take a look at your use case or a minimal reproduction of the issue with repro steps but I won't do so over a call.
